// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieStreamingWinForms.Data;

#nullable disable

namespace MovieStreamingWinForms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518055203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieStreamingWinForms.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2949),
                            Description = "Dream within dreams",
                            IsDeleted = false,
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2951),
                            Description = "Wild bachelor party",
                            IsDeleted = false,
                            ReleaseYear = 2009,
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2953),
                            Description = "Batman vs Joker",
                            IsDeleted = false,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2955),
                            Description = "Space travel",
                            IsDeleted = false,
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2956),
                            Description = "High school graduates",
                            IsDeleted = false,
                            ReleaseYear = 2007,
                            Title = "Superbad"
                        });
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Mind-blowing movie!",
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3025),
                            IsDeleted = false,
                            MovieId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Confusing but great",
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3027),
                            IsDeleted = false,
                            MovieId = 1,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Hilarious! Loved it",
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3028),
                            IsDeleted = false,
                            MovieId = 2,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Best Batman ever",
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3030),
                            IsDeleted = false,
                            MovieId = 3,
                            Rating = 5,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 653, DateTimeKind.Local).AddTicks(4688),
                            Email = "admin@example.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$Uzqm.NB39O/QbQ2nZEFbe.t34C6J5Ws/9wDkN9rxi9wejBYENkyly",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 760, DateTimeKind.Local).AddTicks(7933),
                            Email = "ahmed@example.com",
                            Name = "Ahmed Mansour",
                            PasswordHash = "$2a$11$31ErVezRDwNc0Z7/iQnGcuDYzlaCZIgC8Xfy34Hg1X9tY0ri.vDmy",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(2432),
                            Email = "sara@example.com",
                            Name = "Sara Khalid",
                            PasswordHash = "$2a$11$XPtbaXHUG8mC92IX8s0mse29G4YM2e3RRawj5CJRUmUyg.wXqu.Qy",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Watchlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Watchlists");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            MovieId = 2,
                            AddedDate = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3069)
                        },
                        new
                        {
                            UserId = 2,
                            MovieId = 4,
                            AddedDate = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3070)
                        },
                        new
                        {
                            UserId = 3,
                            MovieId = 1,
                            AddedDate = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3072)
                        },
                        new
                        {
                            UserId = 3,
                            MovieId = 3,
                            AddedDate = new DateTime(2026, 5, 18, 9, 52, 2, 868, DateTimeKind.Local).AddTicks(3073)
                        });
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Movie", b =>
                {
                    b.HasOne("MovieStreamingWinForms.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Review", b =>
                {
                    b.HasOne("MovieStreamingWinForms.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieStreamingWinForms.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Watchlist", b =>
                {
                    b.HasOne("MovieStreamingWinForms.Models.Movie", "Movie")
                        .WithMany("Watchlists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieStreamingWinForms.Models.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.Movie", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("MovieStreamingWinForms.Models.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
